### ISSUE TITLE
Upgrade add default site config

### ISSUE THREAD

**Issue by nemsia** [YunoHost-Apps/grav_ynh#5]
Hello,
On upgrade this app always push the default demo site and remove custom config.

**Comment by tituspijean** [comment]
I think we should use the "update" zips instead. Example : https://github.com/getgrav/grav/releases/download/1.4.8/grav-update-v1.4.8.zip instead of https://github.com/getgrav/grav/releases/download/1.4.8/grav-admin-v1.4.8.zip

Even best, we could use `bin/gpm selfupgrade -f` but it seems we cannot choose the upgraded version. (see https://learn.getgrav.org/basics/installation)

**Comment by tituspijean** [comment]
Confirmed on last commit (9d464b5). Upon upgrade, the whole site is overwritten with the default one.
